#!/bin/bash

module restore
module load PrgEnv-cray
module load craype-accel-amd-gfx90a
module load cpe/24.07
module load rocm/6.1.3
module load cmake cray-python emacs
module unload darshan-runtime
export MPICH_GPU_SUPPORT_ENABLED=1


athenak='/ccs/home/dfielding/athenak-df'
build='/ccs/home/dfielding/athenak-df/build'

cd ${athenak}
cmake -Bbuild -DAthena_ENABLE_MPI=ON -DKokkos_ARCH_ZEN3=ON -DKokkos_ARCH_VEGA90A=ON \
      -DKokkos_ENABLE_HIP=ON -DCMAKE_CXX_COMPILER=CC \
      -DCMAKE_EXE_LINKER_FLAGS="-L${ROCM_PATH}/lib -lamdhip64" \
      -DCMAKE_CXX_FLAGS="-I${ROCM_PATH}/include -munsafe-fp-atomics" 
cd ${build}
make -j
