#!/usr/bin/env python3
"""
Convert AthenaK binary particle output files (.prtclbin) to HDF5 format (.h5)

Usage:
    python prtcl_bin_to_hdf5.py <input.prtclbin> [output.h5]
    
If output filename is not provided, it will be automatically generated by
replacing .prtclbin with .h5
"""

import numpy as np
import h5py
import sys
import os
import read_prtcl_bin as rpb


def convert_prtcl_bin_to_hdf5(binary_filename, hdf5_filename=None, compression='gzip'):
    """
    Convert particle binary file to HDF5 format
    
    Parameters:
    -----------
    binary_filename : str
        Path to input .prtclbin file
    hdf5_filename : str, optional
        Path to output .h5 file. If None, auto-generated from input filename
    compression : str, optional
        HDF5 compression algorithm ('gzip', 'lzf', or None). Default: 'gzip'
        
    Returns:
    --------
    hdf5_filename : str
        Path to created HDF5 file
    """
    
    # Generate output filename if not provided
    if hdf5_filename is None:
        hdf5_filename = binary_filename.replace('.prtclbin', '.h5')
        if hdf5_filename == binary_filename:
            hdf5_filename = binary_filename + '.h5'
    
    print(f"Reading binary file: {binary_filename}")
    data = rpb.read_particle_binary(binary_filename)
    
    print(f"Writing HDF5 file: {hdf5_filename}")
    with h5py.File(hdf5_filename, 'w') as f:
        # Create groups for organization
        metadata_grp = f.create_group('Metadata')
        rdata_grp = f.create_group('ParticleRealData')
        idata_grp = f.create_group('ParticleIntData')
        griddata_grp = f.create_group('GridData')
        
        # Store metadata
        metadata_grp.attrs['time'] = data['time']
        metadata_grp.attrs['dt'] = data['dt']
        metadata_grp.attrs['ncycle'] = data['ncycle']
        metadata_grp.attrs['nparticles'] = data['nparticles']
        metadata_grp.attrs['nrdata'] = data['nrdata']
        metadata_grp.attrs['nidata'] = data['nidata']
        metadata_grp.attrs['ngriddata'] = data['ngriddata']
        
        # Store variable names as string array
        var_names_array = np.array(data['var_names'], dtype='S16')
        metadata_grp.create_dataset('var_names', data=var_names_array)
        
        # Store particle real data (positions and velocities)
        rdata_names = ['x', 'y', 'z', 'vx', 'vy', 'vz']
        for i, name in enumerate(rdata_names):
            if name in data:
                rdata_grp.create_dataset(name, data=data[name], compression=compression)
        
        # Store any additional real data fields
        for key in data.keys():
            if key.startswith('rdata_'):
                rdata_grp.create_dataset(key, data=data[key], compression=compression)
        
        # Store particle integer data (gid, tag, etc.)
        idata_names = ['gid', 'tag', 'lastmove', 'lastlevel']
        for name in idata_names:
            if name in data:
                idata_grp.create_dataset(name, data=data[name], compression=compression)
        
        # Store any additional integer data fields
        for key in data.keys():
            if key.startswith('idata_'):
                idata_grp.create_dataset(key, data=data[key], compression=compression)
        
        # Store grid data at particle locations
        for varname in data['var_names']:
            if varname in data:
                griddata_grp.create_dataset(varname, data=data[varname], 
                                          compression=compression)
    
    # Get file sizes for comparison
    binary_size = os.path.getsize(binary_filename)
    hdf5_size = os.path.getsize(hdf5_filename)
    compression_ratio = 100.0 * (1.0 - hdf5_size / binary_size)
    
    print(f"Conversion complete!")
    print(f"  Binary file size: {binary_size / 1024**2:.2f} MB")
    print(f"  HDF5 file size:   {hdf5_size / 1024**2:.2f} MB")
    print(f"  Compression:      {compression_ratio:.1f}%")
    
    return hdf5_filename


def batch_convert(pattern, compression='gzip'):
    """
    Convert multiple particle binary files to HDF5
    
    Parameters:
    -----------
    pattern : str
        Glob pattern for input files (e.g., "pbin/*.prtclbin")
    compression : str, optional
        HDF5 compression algorithm. Default: 'gzip'
    """
    import glob
    
    files = sorted(glob.glob(pattern))
    if len(files) == 0:
        print(f"No files found matching pattern: {pattern}")
        return
    
    print(f"Found {len(files)} files to convert")
    for i, filename in enumerate(files, 1):
        print(f"\n[{i}/{len(files)}]")
        try:
            convert_prtcl_bin_to_hdf5(filename, compression=compression)
        except Exception as e:
            print(f"ERROR converting {filename}: {e}")


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python prtcl_bin_to_hdf5.py <input.prtclbin> [output.h5]")
        print("\nExamples:")
        print("  python prtcl_bin_to_hdf5.py pbin/TRML.00001.prtclbin")
        print("  python prtcl_bin_to_hdf5.py pbin/TRML.00001.prtclbin output.h5")
        print("\nBatch conversion:")
        print("  python -c 'import prtcl_bin_to_hdf5; prtcl_bin_to_hdf5.batch_convert(\"pbin/*.prtclbin\")'")
        sys.exit(1)
    
    binary_file = sys.argv[1]
    hdf5_file = sys.argv[2] if len(sys.argv) > 2 else None
    
    if not os.path.exists(binary_file):
        print(f"Error: File not found: {binary_file}")
        sys.exit(1)
    
    try:
        convert_prtcl_bin_to_hdf5(binary_file, hdf5_file)
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
