#!/bin/bash
#SBATCH -A AST207
#SBATCH -o galaxy_%j.log
#SBATCH -t 0:59:59
#SBATCH -p batch 
#SBATCH -q normal
#SBATCH -N 512

module restore
module load PrgEnv-cray
module load craype-accel-amd-gfx90a
module load cpe/25.09 cray-mpich/9.0.1 rocm/6.4.2
module load cce/20.0.0
module unload darshan-runtime

export LD_LIBRARY_PATH=${CRAY_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}
export MPICH_ENV_DISPLAY=1
export MPICH_VERSION_DISPLAY=1
export MPICH_GPU_SUPPORT_ENABLED=1
export MPICH_GPU_MANAGED_MEMORY_SUPPORT_ENABLED=1
export MPICH_OFI_NIC_POLICY=GPU
export MPICH_GPU_IPC_CACHE_MAX_SIZE=1000
export MPICH_MPIIO_HINTS="*:romio_cb_write=disable"
export FI_CXI_DEFAULT_CQ_SIZE=131072
export FI_MR_CACHE_MONITOR=kdreg2
export FI_CXI_RX_MATCH_MODE=software
export HSA_XNACK=1

srun -N 512 -n 4096 -c 7 --gpus-per-node=8 --gpu-bind=closest \
	/ccs/home/zunyibrent/Work/athenak/build/src/athena \
	-r phase2/rst/node_00000000/gotham.00006.rst \
	particles/star_prtcl_rst_flag=1 \
	particles/star_particle_file=phase2/rst_prtcl/gotham.00006.rst_prtcl \
	time/tlim=10.6 \
	output2/dt=0.02 \
        output3/dt=0.0025 \
        output4/dt=0.0025 \
        output5/dt=0.0025 \
        output6/dt=0.01 \
        output7/dt=0.01 \
        output8/dt=0.01 \
        output9/dt=0.01 \
        output10/dt=0.01 \
        output11/dt=0.01 \
        output12/dt=0.01 \
        output13/dt=0.01 \
        output14/dt=0.01 \
        output15/dt=0.01 \
        output16/dt=0.0025 \
        output17/dt=0.0025 \
        output18/dt=0.0025 \
        output19/dt=0.0025 \
        output21/dt=0.1 \
        output22/dt=0.1 \
        output23/dt=0.006 \
        output24/dt=0.006 \
        output25/dt=0.006 \
        output26/dt=0.006 \
        output27/dt=0.006 \
        output28/dt=0.006 \
        output29/dt=0.006 \
        output30/dt=0.006 \
        output31/dt=0.006 \
        output32/dt=0.006 \
        output33/dt=0.006 \
        output34/dt=0.006 \
        output35/dt=0.006 \
	-d phase3 -t 0:50:00
