#!/usr/bin/env python3
"""Generate CGL/CGL-LF eigenmode validation inputs for the Figure 17 state."""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import numpy as np


VARIABLES = ("rho", "vx", "vy", "vz", "by", "bz", "ppar", "pperp")


def chi_values(rho0: float, p0: float, k_parallel: float) -> tuple[float, float]:
    cpar = math.sqrt(p0 / rho0)
    chi_perp = math.sqrt(2.0 / math.pi) * cpar / k_parallel
    chi_parallel = math.sqrt(8.0 / math.pi) * cpar / k_parallel
    return chi_parallel, chi_perp


def cgl_matrix(
    rho0: float,
    p0: float,
    bx0: float,
    by0: float,
    bz0: float,
    k_wave: float,
    chi_parallel: float,
    chi_perp: float,
) -> np.ndarray:
    bmag = math.sqrt(bx0 * bx0 + by0 * by0 + bz0 * bz0)
    bhx = bx0 / bmag
    bhy = by0 / bmag
    bhz = bz0 / bmag
    ik = 1j * k_wave

    def rhs(state: np.ndarray) -> np.ndarray:
        rho, vx, vy, vz, dby, dbz, ppar, pperp = state
        delta_p = ppar - pperp
        flux_x = pperp + delta_p * bhx * bhx + by0 * dby + bz0 * dbz
        flux_y = delta_p * bhx * bhy - bx0 * dby
        flux_z = delta_p * bhx * bhz - bx0 * dbz

        out = np.zeros(8, dtype=np.complex128)
        out[0] = -ik * rho0 * vx
        out[1] = -ik * flux_x / rho0
        out[2] = -ik * flux_y / rho0
        out[3] = -ik * flux_z / rho0
        out[4] = -ik * (by0 * vx - bx0 * vy)
        out[5] = -ik * (bz0 * vx - bx0 * vz)

        dbmag_dt = bhy * out[4] + bhz * out[5]
        out[6] = p0 * (3.0 * out[0] / rho0 - 2.0 * dbmag_dt / bmag)
        out[7] = p0 * (out[0] / rho0 + dbmag_dt / bmag)

        q_parallel = -chi_parallel * ik * bhx * (ppar - (p0 / rho0) * rho)
        q_perp = -chi_perp * ik * bhx * (pperp - (p0 / rho0) * rho)
        out[6] += -ik * bhx * q_parallel
        out[7] += -ik * bhx * q_perp
        return out

    matrix = np.zeros((8, 8), dtype=np.complex128)
    for n in range(8):
        basis = np.zeros(8, dtype=np.complex128)
        basis[n] = 1.0
        matrix[:, n] = rhs(basis)
    return matrix


def normalize_eigenvector(
    vector: np.ndarray,
    rho0: float,
    p0: float,
    bx0: float,
    by0: float,
    bz0: float,
) -> np.ndarray:
    bmag = math.sqrt(bx0 * bx0 + by0 * by0 + bz0 * bz0)
    vscale = max(bmag / math.sqrt(rho0), 1.0)
    scales = np.array([rho0, vscale, vscale, vscale, bmag, bmag, p0, p0])
    norm = np.max(np.abs(vector) / scales)
    if norm <= 0.0:
      raise RuntimeError("zero eigenvector")
    vector = vector / norm
    phase_index = int(np.argmax(np.abs(vector) / scales))
    phase = np.angle(vector[phase_index])
    return vector * np.exp(-1j * phase)


def classify_modes(
    eigvals: np.ndarray,
    eigvecs: np.ndarray,
    bx0: float,
    by0: float,
    bz0: float,
    k_wave: float,
) -> dict[str, int]:
    positive = [i for i, val in enumerate(eigvals) if -val.imag > 1.0e-8]
    if len(positive) < 3:
        raise RuntimeError("expected at least three positive-frequency branches")

    e_alfven = np.array([0.0, -bz0, by0], dtype=np.complex128)
    e_alfven /= np.linalg.norm(e_alfven)
    shear_scores = []
    for i in positive:
        vel = eigvecs[1:4, i]
        speed = -eigvals[i].imag / k_wave
        shear = abs(np.dot(e_alfven, vel)) / max(np.linalg.norm(vel), 1.0e-300)
        shear_scores.append((shear, -abs(speed - abs(bx0)), i))
    alfven = max(shear_scores)[2]

    compressive = [i for i in positive if i != alfven]
    compressive.sort(key=lambda i: -eigvals[i].imag / k_wave)
    return {"slow": compressive[0], "fast": compressive[-1], "alfven": alfven}


def format_float(value: float) -> str:
    return f"{value:.17e}"


def input_text(
    *,
    name: str,
    branch: str,
    vector: np.ndarray,
    eigenvalue: complex,
    lf: bool,
    nx1: int,
    tlim: float,
    amp: float,
    rho0: float,
    p0: float,
    bx0: float,
    by0: float,
    bz0: float,
    k_wave: float,
    rel_tol: float,
) -> str:
    lines = [
        f"# Exact {branch} eigenmode check for the Squire et al. Figure 17 background.",
        "# Eigenvectors are generated by scripts/generate_cgl_lf_eigenmode_inputs.py.",
        "# The eigenvalue lambda uses Fourier convention d(delta U_k)/dt = lambda delta U_k.",
        "",
        "<job>",
        f"basename = {name}",
        "",
        "<mesh>",
        "nghost = 2",
        f"nx1 = {nx1}",
        "x1min = 0.0",
        "x1max = 1.0",
        "ix1_bc = periodic",
        "ox1_bc = periodic",
        "nx2 = 1",
        "x2min = 0.0",
        "x2max = 1.0",
        "ix2_bc = periodic",
        "ox2_bc = periodic",
        "nx3 = 1",
        "x3min = 0.0",
        "x3max = 1.0",
        "ix3_bc = periodic",
        "ox3_bc = periodic",
        "",
        "<meshblock>",
        f"nx1 = {nx1}",
        "nx2 = 1",
        "nx3 = 1",
        "",
        "<time>",
        "evolution = dynamic",
        "integrator = rk2",
    ]
    if lf:
        lines.extend([
            "sts_integrator = rkl2",
            "sts_max_dt_ratio = -1.0",
        ])
    lines.extend([
        "cfl_number = 0.15",
        "nlim = -1",
        f"tlim = {format_float(tlim)}",
        "ndiag = 1",
        "",
        "<mhd>",
        "eos = cgl",
        "passive = false",
    ])
    if lf:
        lines.extend([
            "cgl_heat_flux = landau_fluid",
            "cgl_heat_flux_integrator = sts",
            f"lf_k_parallel = {format_float(k_wave)}",
            "lf_coefficient_mode = background",
            f"lf_c_parallel0 = {format_float(math.sqrt(p0 / rho0))}",
            "cgl_lf_strict_admissibility = true",
        ])
    lines.extend([
        "reconstruct = plm",
        "rsolver = hlle",
        "gamma = 1.666666666666667",
        "dfloor = 1.0e-12",
        "pfloor = 1.0e-12",
        "tfloor = 1.0e-12",
        "sfloor = 1.0e-12",
        "bfloor = 1.0e-10",
        "",
        "<problem>",
        "pgen_name = cgl_landau_fluid",
        "test_mode = paper_eigen_wave",
        f"eigen_branch = {branch}",
        "mode_number = 1",
        f"rho0 = {format_float(rho0)}",
        f"ppar0 = {format_float(p0)}",
        f"pperp0 = {format_float(p0)}",
        f"b0 = {format_float(bx0)}",
        f"by0 = {format_float(by0)}",
        f"bz0 = {format_float(bz0)}",
        f"amp = {format_float(amp)}",
        f"eigen_lambda_re = {format_float(eigenvalue.real)}",
        f"eigen_lambda_im = {format_float(eigenvalue.imag)}",
        f"eigen_wave_rel_tol = {format_float(rel_tol)}",
        "eigen_component_floor = 1.0e-4",
        "eigen_zero_abs_tol = 1.0e-8",
    ])
    for label, value in zip(VARIABLES, vector):
        lines.append(f"eigen_{label}_re = {format_float(value.real)}")
        lines.append(f"eigen_{label}_im = {format_float(value.imag)}")
    lines.extend([
        "validation_output = false",
        "validation_output_dir = docs/figures/data",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("inputs/unit_tests"))
    parser.add_argument("--nx1", type=int, default=256)
    parser.add_argument("--tlim", type=float, default=2.0e-3)
    parser.add_argument("--amp", type=float, default=1.0e-5)
    parser.add_argument("--rel-tol", type=float, default=7.5e-2)
    args = parser.parse_args()

    rho0 = 1.0
    p0 = 5.0
    bx0 = 1.0
    by0 = math.sqrt(2.0)
    bz0 = 0.5
    k_wave = 2.0 * math.pi
    args.output_dir.mkdir(parents=True, exist_ok=True)

    for closure in ("pure", "lf"):
        chi_parallel = chi_perp = 0.0
        if closure == "lf":
            chi_parallel, chi_perp = chi_values(rho0, p0, k_wave)
        matrix = cgl_matrix(rho0, p0, bx0, by0, bz0, k_wave, chi_parallel, chi_perp)
        eigvals, eigvecs = np.linalg.eig(matrix)
        branches = classify_modes(eigvals, eigvecs, bx0, by0, bz0, k_wave)
        for branch, index in branches.items():
            vec = normalize_eigenvector(eigvecs[:, index], rho0, p0, bx0, by0, bz0)
            name = f"cgl_{closure}_paper_eigen_{branch}"
            path = args.output_dir / f"{name}.athinput"
            path.write_text(
                input_text(
                    name=name,
                    branch=branch,
                    vector=vec,
                    eigenvalue=eigvals[index],
                    lf=(closure == "lf"),
                    nx1=args.nx1,
                    tlim=args.tlim,
                    amp=args.amp,
                    rho0=rho0,
                    p0=p0,
                    bx0=bx0,
                    by0=by0,
                    bz0=bz0,
                    k_wave=k_wave,
                    rel_tol=args.rel_tol,
                )
            )
            speed = -eigvals[index].imag / k_wave
            print(f"{path}: lambda={eigvals[index]:.8e}, phase_speed={speed:.8e}")


if __name__ == "__main__":
    main()
